In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
from keras import Sequential

In [3]:
from keras.layers import Dense,SimpleRNN

In [4]:
model=Sequential()

In [5]:
# 3 nodes 
# Maximum 4 timestamp and input_features is 5
model.add(SimpleRNN(3,input_shape=(4,5)))
# Since we are working with Binary Classificatin we take Sigmoid function as Activation function
model.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [6]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)               │ (None, 3)                   │              27 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1)                   │               4 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 31 (124.00 B)

 Trainable params: 31 (124.00 B)

 Non-trainable params: 0 (0.00 B)

In [8]:
print(model.get_weights()[0].shape)
model.get_weights()[0]

(5, 3)


array([[-0.6844398 ,  0.16214496,  0.44420022],
       [-0.5403303 ,  0.75014025,  0.6976357 ],
       [ 0.26284343,  0.3526289 , -0.8350663 ],
       [ 0.20936555, -0.7382263 ,  0.11708313],
       [-0.5792237 , -0.71965975, -0.39446703]], dtype=float32)

## Between Inputs and SimpleRNN there 15 weights

In [9]:
print(model.get_weights()[1].shape)
model.get_weights()[1]

(3, 3)


array([[-0.52963245,  0.43727732,  0.7268274 ],
       [-0.7690191 , -0.6090989 , -0.19392839],
       [-0.35790923,  0.66165495, -0.6588731 ]], dtype=float32)

## Feedback Connection

In [10]:
print(model.get_weights()[2].shape)
model.get_weights()[2]

(3,)


array([0., 0., 0.], dtype=float32)

## 3 biases

In [11]:
print(model.get_weights()[4].shape)
model.get_weights()[4]

(1,)


array([0.], dtype=float32)

# THANKS